apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      # Job 1: Self-Scrape
      - job_name: 'prometheus-self' 
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'microservices-static' 
        metrics_path: /actuator/prometheus 
        static_configs:
          - targets:
            - 'apigateway-service:80'    
            - 'discovery-service:8761'   
            - 'recomendation-service:8082' 
            - 'booking-service:8080'